### ISSUE TITLE
Fixes for upstream changes

### ISSUE THREAD

**Issue by layus** [highlightjs/highlightjs-oz#2]
- [x] Your primary JS file should only set a default export, no others
- [x] Remove any other definer and/or other additional exports
- [x] Your repository should include a `dist` folder with pre-built CDN assets. Reference: [3RD_PARTY_QUICK_START.md.md](https://github.com/highlightjs/highlight.js/blob/master/extra/3RD_PARTY_QUICK_START.md)
- [x] Remove any browser shims from your raw JS source
- [x] Consider adding a `package.json` and publishing your grammar on [NPM](https://www.npmjs.com) if you aren't already
- [x] Please update your `README.md` if necessary to reflect these changes
- [x] Remove `charset="UTF-8"` from your examples, it should no longer be necessary with `dist` builds produced by our build tools

**Comment by joshgoebel** [comment]
Your README still mentions UTF-8.

**Comment by layus** [comment]
@joshgoebel Thanks, I am still trying to figure out how to build this. At the moment the tools/developer.html does not work, and the auto-detection conflicts with "properties", which has basically no relevance tags, so gets ambiguous with everything else :-)

The readme is the least of my problems, especially given that I had to delete build/ to get it to rebuild things correctly. A mess :-/

**Comment by joshgoebel** [comment]
> At the moment the tools/developer.html does not work

It requires a browser build, not node, etc... `build -t browser` if you want to play around with your grammar with the developer tool.

> and the auto-detection conflicts with "properties", which has basically no relevance tags, so gets ambiguous with everything else :-)

Auto-detect is a whole other ball of wax and you shouldn't really expect to make those tests happy (we barely do ourselves).  If you are certain you don't do it well at all (auto-detect), you can just disabled autodetect for your grammar... or if you think it's just the tests being prickly, then just ignore those failures.

You can build `cdn` (and get your `dist` build) whether or not all the tests are green.  The tests are most useful for the regex ReDOS security testing. (or any markup tests you might have)

> especially given that I had to delete build/ to get it to rebuild things correctly

Hmmm... the build script should do that automatically...

**Comment by layus** [comment]
@joshgoebel  Thanks for the info :-)

**Comment by layus** [comment]
Notes for my future self:

:warning: Builds overwrite the `build/` directory, each build produces different, sometimes incompatible outputs

- setup the build env (maybe turn it into a nix-shell ?) `nix-env -f "<nixpkgs>" -iA nodejs nodePackages.typescript nodePackages.npm nodePackages.npm-check-updates nodePackages.mocha`
- highlightjs-oz resides in highlight.js/extra/, everything is build from top-level highlight.js
- to run tests, run `npm run build; npm run tests`
- check that both detection and markup tests run. markup tests require a corresponding `foo.expect.bar` for each `foo.bar` file to test.
- to build cdn files, run `node ./tools/build.js -t cdn`
- to build a local dev build, run `node ./tools/build.js; firefox tools/developer.html`
- To release, bump the version number and `npm login; npm publish`
- `10` is quite a high relevance, use lower values when possible :-D

Useful links
- https://highlightjs.readthedocs.io/en/latest/building-testing.html#basic-testing
- https://github.com/highlightjs/highlight.js/blob/master/extra/3RD_PARTY_QUICK_START.md
- https://github.com/highlightjs/highlight.js/issues/3008
- https://github.com/highlightjs/highlight.js/blob/master/docs/language-guide.rst
- https://github.com/highlightjs/highlight.js/blob/master/docs/language-contribution.rst

**Comment by layus** [comment]
Fixed in https://github.com/highlightjs/highlightjs-oz/commit/00084fd371e5eb9047096ca8196d0ce2bc3ed71c

**Comment by joshgoebel** [comment]
>  each build produces different, sometimes incompatible outputs

Are you just referring to browser vs node vs CDN actually being very different build products?  What behavior would you expect instead?

**Comment by layus** [comment]
> > each build produces different, sometimes incompatible outputs
> 
> Are you just referring to browser vs node vs CDN actually being very different build products? What behavior would you expect instead?

Yes, exactly.

I would expect these build variants to output to different directories or subdirectories like build-cdn and build-browser, or build/{browser,cdn,node}. 

This would ensure that the layout of the build directory remains stable. And that (for example) the `tools/developer.html` refers to a file that is not deleted by the next, different build.

Going further, it would make sense to have a proper build system, or at least a single entry point for all the builds. Not too knowledgeable about js build systems but Grunt looks like an easy goal.
That way, running one command ensure that all the builds are performed. That way you know that after invoking the build system, every product is up to date, and `tools/developer.html` (as well as all the other outputs) refer to the most recent version. Because the only thing that could be worse than the current situation is having three build folders but only one up-to-date. It would be a nightmare to access `tools/developer.html` and dscover only after a while that it is not up-to-date.

Not sure which is the best way forward. In fact, everything is already quite clear in 3RD_PARTY_QUICK_START.md, and it is mostly me carrying over some incomplete, previous knowledge of the project.

**Comment by joshgoebel** [comment]
> I would expect these build variants to output to different directories or subdirectories like build-cdn and build-browser, or build/{browser,cdn,node}.

`./tools/build.js -t all` does that IIRC.  :-)

Though there could be bugs (and the other things aren't expecting those paths), I've never really used it.  99% of the time I don't want or need everything built, only the target I'm working on at the moment.  Perhaps that would be a more reasonable default even when not using "all"... sometimes I do get annoyed that one build flushes another (node vs browser), but it's never risen to the point of fixing it.

> or at least a single entry point for all the builds. 

I'm not sure I follow... Isn't that what `tools/build.js -t [target]` is?

> Not too knowledgeable about js build systems but Grunt looks like an easy goal.

Very uninterested in another build system. We also have some pretty specific requirements.  I wrote the one we have now by hand to be "plain understandable javascript" and do exactly what we need it to do - replacing the previous "tons of magic" system.  So far it's proven simple and easy to maintain.

**Comment by layus** [comment]
It makes a lot of sense, and the current behavior, even if it was frustrating, was at least very good at hinting me that something was wrong in my usage.

The presence of the build directory is a bit misleading, as in that case you would expect all the build outputs to go in there. But cdn puts the cdn files in extra/*/dist.

I was also confused because the docs (https://highlightjs.readthedocs.io/en/latest/building-testing.html#) has `npm run build` and `npm run test` as a second entrypoint.

This discussion is starting to look like a rant, and I do not want that at all. The project is great, and the revival of interest in it is just awesome! If my explanations can help, great :-). But please stop me if it does not.

**Comment by joshgoebel** [comment]
> The presence of the build directory is a bit misleading, as in that case you would expect all the build outputs to go in there. But cdn puts the cdn files in extra/*/dist.

Only those from 3rd parties...  That was done on purpose for packagers convenience... and to encourage the convention. :-)  Doesn't it put them in build ALSO?  _The build should still be complete._  The `dist` placement is a "convenience" for 3rd party maintainers.  I think the output mentions that it's doing that explicitly - or am I misremembering?

It's possible the docs could be improved as well.

> has npm run build and npm run test as a second entrypoint.

`build` vs `test`, is that unusual?  I think that's pretty common. Feel like I'm missing something here?

> The project is great, and the revival of interest in it is just awesome!

Thanks! We try!

>  If my explanations can help, great :-). But please stop me if it does not.

Well, that's what I'm trying to discern with my questions. :)  I ask questions because sometimes I'm too close to everything too see some things clearly.  You may have persuaded me (so far) that sep build directories (as a default) would have a few advantages.

**Comment by layus** [comment]
> > has npm run build and npm run test as a second entrypoint.
> 
> `build` vs `test`, is that unusual? I think that's pretty common. Feel like I'm missing something here?

My confusion was the difference between `node ./tools/build.js -t something`  and `npm build` ? Is there any ? Why is there a node entry point, and a npm one ? Can we `npm build -t cdn` ?

> The dist placement is a "convenience" for 3rd party maintainers. I think the output mentions that it's doing that explicitly - or am I misremembering?

It does, that part was easy to discover and understand :-).

**Comment by joshgoebel** [comment]
> My confusion was the difference between node `./tools/build.js` -t something and npm build ? Is there any ? 

Not really, you're just seeing package.json `scripts` in action. https://docs.npmjs.com/cli/v7/using-npm/scripts

> Why is there a node entry point, and a npm one ? 

This is almost always the case.  `npm` scripts are just for "convenience", they always point to a "real" node entry point ... I usually just use the actual underlying command myself - some prefer the shortcuts.  If you're larger point is our docs aren't consistent that might be worth review.

> Can we npm build -t cdn ?

I'm not sure, but I haven't seen that done.  Instead often people create additional `scripts`, as we do:

- build-cdn
- build-browser
- build_and_test

etc.

**Comment by layus** [comment]
Thanks for all the clarifications :-). Now it makes sense to me, but I am not too sure what to do to share that knowledge. I may PR 3RD_PARTY_QUICK_START.md to include some findings.
